Microsoft/mattercenter

- README.md
> Corrected spelling of 'Feedback'

- README.md
> Corrected SharePoint branding

- tree/master/cloud/src/deployments/Scripts/AppInstall.ps1
- tree/master/cloud/src/deployments/Upgrade from Preview/AppInstall.ps1
Remove BETA from SharePoint app name from App Install PS1 during first time install and Upgrade scripts.
> Update app install ps1 file

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
- Added dropdowns in Matters page 
- Added css in site.css
- Done changes for UI-grid in matter controller
> New Changes

- README.md
Added tag to enable better tagging on the referrers
> Added the tag as provided by product team

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/app.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matter.resources.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/index.html
1. In Index.html Added the createMatter.controller.js file ref.
2.In matter.resources.js added the taxanomy api details.
3.New file named as createMatter.controller.js is added to the project.
4. New file createMatter.html is added to the project.
5. In navigation.html added the url route for createMatter links.
6.written few custom css classes in site.css
> 1. Added createMatter.controller.js ref in Index.html

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.html
Added functionality changes in the createMatter page for selectType
> Added the functionality for openmatter page selectType changes

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/MatterProvision.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/index.html
Added the new functionality changes to the creatematter page.
> Commiting the new functinality changes in create matter page

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/CommonControls.css
2.Worked on popover click issue and now click is working successfully.
3.Worked on showing pinned and unpinned on clicking the ellipsis
4.Worked on some css part
> 1. Worked on responsive design changes.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2. Worled on popover functionality in bootstrap.
3.Worked on some changes in css
> 1. Worked on some functionality in modal popup for Documents and Emails

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/CommonControls.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/FilterPanel.css
2. Done small changes for grid in documents controller
3. Done changes in matters.html,matters.controller.js,commonControls.css,Filterpanesl.css,site.css,documents.controller.js
> 1. Worked on css in angular Ui-grid, dropdown and search box in matters.html page

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/app.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2.Worked on custom sorting functionality.
3. Worked on design in the ellipsis dropdown,
4.Worked on other angular code for displaying the down arrow on hovering the grid header cell and also worked on other css
> 1. Worked on design in popover of the ui-grid.

- README.md
> Update Contibutors section

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
Corrected the dropdown issue in matters page
> Mattercenter2

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/CreateMatter.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/index.html
committing the validation messages and success messages functions
> committing the validation functions and success messages

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.resources.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/ClientHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/ClientMatterHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/ModifiedDateTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/OpenDateHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/ResponsibleAttorneyHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/SubAreaHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/services/api.service.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/index.html
2. Added new html pages for the headers of the grid in matters page.
3. Removed the profile pic and contextual help code from navigation,matter and documents page.
4. Added the profile and contextual help code in home.html page to display in all pages.
5. Added new resource js file for home controller and other respective changes.
> 1. Done changes for sorting functionality in matters controller

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/DocumentTemplates/ClientHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/DocumentTemplates/DocumentHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/DocumentTemplates/ModifiedDateHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/ClientHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/ModifiedDateTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2. Done changes for filters in headertemplates in matters page and documents page.
3. Added some css for gridmenu in matters and documents page.
4. Added code for fixing the dynamic width for the grid in matters page
5. Done changes for other small issues in matters and document page.
> 1. Done changes for flyout links in documents page .

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterCellTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/index.html
2.  Replaced the hardcoded url with dynamic code in mattercelltemplate.
3.  Removed the directives from controllers and added the new js for directives under directives folder and done changes as per that.
> 1.  Added some functionality for search in matters and documents page.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2. Added and replaced some changes for the grid menu and other changes in matters and documents in css.
> 1. Done changes for the grid in responsive for documents page .

- .gitignore
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/DocumentProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/Upload/UploadHelperFunctions.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/Upload/UploadHelperFunctionsUtility.cs
Fixed the bugs in the upload emails and attachments from OWA
> Fixed the bugs in the upload emails and attachments from OWA

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/DocumentTemplates/DocumentCellTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2. Fixed the click issue on buttons in flyout issue in documents and matters page.
3. Fixed some css issues in matters page.
> 1. Done changes in directives for testing some functionality.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterCellTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
2. Added the functionality for infinite scroll in documents page.
3. Added code for custom flyout in matters page.
4. Replaced the link for view matters in mattercelltemplate.
> 1. Done changes to show the loader when scrolling in matters page.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/app.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/DocumentTemplates/DocumentCellTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterCellTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2. Done changes for the css to make flyout visible as per the responsive design in both matters and documents page.
3. Fixed the scroll issues in both matters and document pages.
4. Moved the directive code from matters page to common.directives page.
> 1. Implemented custom flyout in document page.

- .gitignore
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/IntegrationTests/AttachmentUnitTest.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/IntegrationTests/DocumentUnitTest.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/IntegrationTests/ExternalSharingUnitTest.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/IntegrationTests/MatterUnitTest.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/IntegrationTests/SharedUnitTest.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/IntegrationTests/TaxonomyUniTest.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/IntegrationTests/UserUnitTest.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/Microsoft.Legal.MatterCenter.ServiceTest.xproj
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/Program.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/Startup.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.ServiceTest/project.json
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.sln
Migrating and including Test project on RC2
> Migrating Test Project on RC2

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/Taxonomy.cs
Added code to support 5 level of taxonomy hierarchy
Associate parent term custom properties to child term, if the custom properties are not available for the child terms
> Added code to support 5 level of taxonomy hierarchy

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.resources.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.html
2. Added typehead code for search and author search in documents  dashboard page.
3. Done changes for the pagination errors in matters and document dashboard pages.
> 1. Added typehead code for search in matters dashboard page.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/config.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/AreaofLawHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterCellTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/OpenDateTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/ResponsibleAttorneyHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/uiconfig.js
1. Added changes to get the dynamic content in Matters and navigation pages.
2. Replaced html text with dynamic content for matters templates.
3. Added some changes in create matters controller
> Added changes to update some text with the dynamic content.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Startup.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/appsettings.json
Added code to update the config.js using NewtonSoft.json package
> Added code to update the config.js using NewtonSoft.json package

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterCellTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
1. Added changes in matters.html and matters controller pages for getting the dynamic values from config.
2. Done changes to the scope variables in navigation html, controller and matter template pages.
> Replaced hard coded values to the dynamic values from config

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/uiconfig.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2. Added changes for the grid menu functionality in matters and documents pages.
3. Added new directive in common directives for the grid menu to work in responsive.
4. Replaced hardcoded values with dynamic values in matters and navigation pages.
> 1. Added new css styles for the grid menu in site.css.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/uiconfig.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/index.html
1. Added new css for the grid menu for some icons
2. Added fucntionality for the export grid data to the excel in matterdashboard page.
3. Done changes for the some directives related to the grid menu to show and hide the icons.
4. Added plugin references of the exporting excel in index page
> Replaced grid menu css in matters and dashboard pages.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2. Fixed some design issues for the menu in matter and documents.
3. Fixed the errors in matters and documents after changing the hardcoded values with uiconfig values.
> 1. Fixed the issues for the column picker in matters and documents.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterCellTemplate.html
Changes to resolve the bug Bug 1057863:Alignment issue at ellipsis menu.
> Changes to resolve the bug Bug 1057863:Alignment issue at ellipsis menu.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/settings.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/settings.html
Configuring static content to azure table for Settings page.
> Configuring static content to azure table for Settings page.

- tree/master/cloud/src/solution/Deployment/Deployment.deployproj
- tree/master/cloud/src/solution/Deployment/Scripts/Create-AzureStorageTable.ps1
- tree/master/cloud/src/solution/Deployment/Scripts/ManageTableStorageWithCsvFile/AzureStorageTable.csv
- tree/master/cloud/src/solution/Deployment/Scripts/ManageTableStorageWithCsvFile/ManageTableStorageWithCsvFile.psd1
- tree/master/cloud/src/solution/Deployment/Scripts/ManageTableStorageWithCsvFile/ManageTableStorageWithCsvFile.psm1
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
script to import config files to storage table
> Mattercenter2  script to import config files to storage table

- tree/master/cloud/src/solution/Deployment/Scripts/Deploy-AzureResourceGroup.ps1
- tree/master/cloud/src/solution/Deployment/Scripts/KeyVault-Config.ps1
- tree/master/cloud/src/solution/Deployment/Templates/template.json
Changes for Uploading Certificate to Wesite
> Changes for Uploading Certificate to Wesite

- tree/master/cloud/src/solution/Deployment/Scripts/Deploy-AzureResourceGroup.ps1
- tree/master/cloud/src/solution/Deployment/Scripts/KeyVault-Config.ps1
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/Search.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Utility/ConfigSettings/SearchSettings.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/MatterProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/appsettings.json
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.jobs/Functions.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.jobs/appSettings.json
Added code for search related to level 4 and level 5
Fixed the height issue in matter search results
Added code for matter web app settings deployment
> Added code for matter web app settings deployment

- tree/master/cloud/src/solution/Deployment/Scripts/Deploy-AzureResourceGroup.ps1
> Mattercenter2 - Fix for Result source ID

- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.MatterCenter.UpdateAppConfig/UpdateConfig.cs
Refactored how the bug was fixed, as now there's no need for the Else if condition.
> Issue #387 fix refactored

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/cellCheckboxTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/settings.controller.js
Fixed Check box checking functionality and cart count on slection
Fixed only selected documents visible on click of cart image
Fixed on uncheck of document cart should remove the document
Fixed lamda expression issue on Settings controller for IE.
> Changes required to resolve the bug 1205410

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
Changes to resolve 1213401 and Bug 1209059
Changes for Date filter functionality  to work as per expected in Matters and Document Search page.
> Changes to resolve 1213401 and Bug 1209059

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Models/Search/SortObject.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/Document/DocumentRepository.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/ICommonRepository.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/Matter/MatterRepository.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/Interfaces/ISearch.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/Search.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/DocumentProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/Interfaces/ISharedProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/MatterProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Controllers/DocumentController.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Controllers/MatterController.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
Updated Search API and UI controllers 
Fixed some existing issues in the UI controllers around sorting
> Fix for 1214132  Incorrect implementation of sort functionality

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/FilterPanel.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/MatterProvision.css
2. Refactored the code for sorting method in documents page.
3.  Done changes in documents and dashboard pages for sorting to work in pinned tabs
> 1. Fixed the 1290175, 1270974, 1285897, 1285621, 1285761, 1278147 bugs

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
Changes to remove duplicate values in column filters.
Changes to get proper filter values after selection of item in filters container.
> Changes to remove duplicate values in column filters

- tree/master/cloud/src/solution/Deployment/Scripts/ManageTableStorageWithCsvFile/AzureStorageTable.csv
Added new UI labels in CSV to update them during deployment. If you already deployed, import this CSV directly to 'MatterCenterConfiguration' azure storage table.
> updated labels

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/ValidationFunctions.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/appsettings.json
Changes to make matter dashboard page responsive.
> Changes to make matter dashboard page responsive.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/appsettings.json
CSS changes required to make  page responsive.
> Changes done for making document dashboard page responsive.

- tree/master/cloud/src/solution/Deployment/Scripts/ManageTableStorageWithCsvFile/AzureStorageTable.csv
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/Home.css
Make icon configurable at home page.
Make MatterCenter logo Configurable on DocumentDetails page
Make MatterCenter logo Configurable on MatterDetails page
Correct the sort order of pinned Documents.
Changes to Section title and View More link to work on DocuemntDetails page.
Search on Project Type column filter properly.
> Changes to make project configurable and some issues..

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/Search.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
Changes to display Filters results on document search page with Document ID.
Changes  to modify string values.
Changes to get results in column filters in pinned documents after code modification.
> Changes to display Filters results on document search page with Document ID.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Models/Users/Users.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/Search.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/UserRepository/UserRepository.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/MatterProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Controllers/MatterController.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
Changes to Get author filter in document dashboard with role.
Changes to get correct sorting data on created date on document and project dashboard.
Changes to get Columfilter values in Project Center for same column where filter applied.
> Changes to Get author filter in document dashboard with role.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/Search.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/DocumentProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/MatterProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
Changes to make all column filter case insensitive.
Changes to get Column filter results fast by optimizing request.
Changes to hide Column filter Popup on clicking on Column for sorting in Document and Matter Search page.
Changes to get all possible column results on filtered column for resetting filter by selecting new values.
Changes to display and search by document ID in document dashboard page.
> Changes to display and search by document ID in document dashboard page.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/app.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
Changes to Clear text in column filter on click outside and on click on column for sorting
Chnages to show document flyout after getting data.
Changes to show correct order for pinned document and matters on loading.
> Changes to Clear text in column filter on click outside and on click on column for sorting

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
2. Fixed the loading issues in matters page.
3. Fixed the menu overlapping issue with flyout in matters and documents pages.
4. Fixed the other Ui design issues of column headers in matters and document pages.
> 1. Fixed the User profile cutting issue in lower resolutions.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Utility/Utility/SearchUtility.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/DocumentProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Controllers/TaxonomyController.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/appsettings.json
Updated code for & decinmal unicode issue
Checking null for docid
Caching the taxonomy data
> Fixing search issues

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/CreateMatter.css
Changes to show Loading image when document flyout is loaded for the first time after page load
Changes to remove overlapping on  Success message and popup for user profile on Matter creation page.
> Changes to show Loading image when document flyout is loaded for the first time after page load

- tree/master/cloud/src/solution/Deployment/Scripts/Deploy-SPOFiles.ps1
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.html
moved show-message function definition to top and corrected libraryfunctions.ps1 path.
> fixed show-message error

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/appsettings.json
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
Added practice group to the pinned matter
Fixed the matter id and client id for the grid
> Added practice group to the pinned matter

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Startup.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/appsettings.json
Added new sections to the appsettings json file for upload messages
Modified startup.cs file to include the upload message section into the config.js file
> Added new sections to the appsettings json file for upload messages

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
Changes to get correct from date and end date on enter and tab out event with different conditions..
Changes to disable from date options greater then end dates.
> Changes to get correct From & To date on enter and tab out event with different conditions..

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/settings.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/settings.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/viewspecific/FilterPanel.css
2. Fixed the white space issue in matters page.
3. Fixed the pagination ui issue in document dashboard page.
> 1. Fixed the footer issue in settings page.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/admin/admin.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/app.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/settings.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/drop.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/heading.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matterusers.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
Fixed clear filter issue in mattersearch.
Remove all commented code
> Remove all commented code

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Controllers/MatterController.cs
Hard coding of true has been removed when checking whether the login user can create matter or not
> Hard coding of true has been removed when checking whether the login user can create matter or not

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/documentdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/matterdashboard.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
Proper comments given to functions and variables with suggested changes in JS files
> Decorate function with proper comments with suggested changes.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Jasmine/Object/ObjectCollection.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Jasmine/Object/mockObjects.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Jasmine/Specs/CreateMatterController.spec.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Jasmine/Specs/DocumentController.spec.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Jasmine/Specs/MatterController.spec.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Jasmine/Specs/MatterControllerservicecall.spec.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Jasmine/Specs/MatterDashboardControllerservicecall.spec.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Jasmine/Specs/SettingsController.spec.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/dashboard/settings.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
Changes to pass Jasmine test cases.
> Changes to pass Jasmine test cases.

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Models/Matter/MatterInformationVM.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/Matter/IMatterRepository.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/Matter/MatterRepository.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/SPList.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Utility/Constants/UploadEnums.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/Interfaces/IMatterProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/MatterProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/ValidationFunctions.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Controllers/MatterController.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matter.resources.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matterusers.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matterusers.html
Code changes for improving the matter users screen performance
> Code changes for improving the matter users screen performance

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matterusers.controller.js
Reverts Microsoft/mattercenter#666
> updated user deletion feature

- tree/master/cloud/src/deployments/Static Content/Matter Center Assets/Matter Landing Assets/scripts/MatterLanding.js
Fixed the issue related to calendar and task url in matter landing page
> Fixed the issue related to calendar and task url in matter landing page

- tree/master/cloud/src/solution/Deployment/Scripts/ManageTableStorageWithCsvFile/AzureStorageTable.csv
…Addition of new entries in AzureTableStorage for Additional matter properties.
> Addition of new entries in AzureTableStorage for Additional matter properties.

- tree/master/cloud/src/deployments/Static Content/Matter Center Assets/Document Landing Assets/Scripts/documentDetails.js
- tree/master/cloud/src/deployments/Static Content/Matter Center Assets/Matter Landing Assets/scripts/MatterLanding.js
- tree/master/cloud/src/solution/Deployment/Scripts/ManageTableStorageWithCsvFile/AzureStorageTable.csv
Changes for Task and extraproperties
> Changes for Task and extraproperties

- tree/master/cloud/src/solution/Deployment/Scripts/ManageTableStorageWithCsvFile/AzureStorageTable.csv
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/documents.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/createMatter.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
Changes to resolve Accessibility issues.
> Changes to resolve Accessibility issues.

- tree/master/cloud/src/deployments/Static Content/Matter Center Assets/Matter Landing Assets/scripts/MatterLanding.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/SharePointInfo/Extensions/ContentTypeExtensions.cs
Updated the tasks and calendar code to fix the loading issue. Loading icon will be removed after we get the data from the SPO
Previously, the loading icon code was getting called after data was fetched from the SPO. So the data was getting overwritten with the data that gas been retrieved from the SPO
Added null check for content type
> Updated the tasks and calendar code to fix the loading issue

- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.MatterCenter.CreateTerm/CreateTerm.cs
To avoid duplication. Might consider having here advanced wait method to be implemented which checks the state of creation.
> Added Sleep timer to allow terms to be created 

- .gitignore
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Service/Microsoft.Legal.MatterCenter.Repository/Matter/MatterRepository.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matterusers.controller.js
Code changes for matter users screen to handle some corner case scenarios
> Code changes for matter users screen to handle some corner case scenarios

- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/directives/common.directive.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/document/DocumentTemplates/DocumentCellTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/home.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/MatterTemplates/MatterHeaderTemplate.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.controller.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/matter/matters.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/navigation.html
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/app/uiconfig.js
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/css/site.css
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/wwwroot/index.html
Code changes for accessibility fixes
> Code changes for accessibility fixes

- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.MatterCenter.HelperUtilities.sln
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Microsoft.Legal.ProjectCenter.UpdateProjectName.xproj
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Models/DocumentData.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Models/Project.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Models/ProjectData.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Models/UserInfo.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Program.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Properties/AssemblyInfo.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/SharePointInfo/SpList.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Utilities/Constants.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Utilities/Enums.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/Utilities/Utilities.cs
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/appsettings.json
- tree/master/cloud/src/Helper Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.ProjectCenter.UpdateProjectName/project.json
Added a new project to the helper utilities which will help in updating the matter name
> Added a new project to the helper utilities which will help in updating the matter name

- tree/master/cloud/src/solution/Deployment/Scripts/Deploy-AzureResourceGroup.ps1
> Fixed tenant retrieval

- tree/master/cloud/src/solution/Deployment/Scripts/Deploy-AzureResourceGroup.ps1
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Common/MatterProvision.cs
- tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.Web/Controllers/DocumentController.cs
> Fixes for errors when matters load and documents uploaded in web explorer
